### ISSUE TITLE
Time maybe inaccurate when the refresh() called after update() called immediately 

### ISSUE THREAD

**Issue by kevindiu** [kpango/fastime#18]
If the time is refreshed and at the same time the update ticker was received, the time will incorrect until next refresh() called.

https://github.com/kpango/fastime/blob/827f81927634d8f457b78a07febb4856ab2ae177/fastime.go#L205

Purpose:

                        upd:= false
			case <-ticker.C:
                                if upd {
				      f.refresh()
                                      upd = false
                                } else {
                                     f.update
                                }
			case <-ctick.C:
				upd = true

**Comment by kpango** [comment]
I think select case cannot receive ticker at the same time

**Comment by kevindiu** [comment]
For example:

ticker duration: 100ms (ticker to call update())
ctick duration: 200ms (ticker to call refresh())
At 200ms, There is a chance that ctick.C come first before receive ctick, so the refresh is called. After that the  updTicker will be received and trigger the update() call immediately. At this time the time is not accrete and have 100ms difference.

**Comment by kpango** [comment]
hmm

**Comment by kevindiu** [comment]
Another purpose:

                f:= f.update
		case <-ticker.C:
                            f()
                            f = f.update
		case <-ctick.C:
			f = refresh

**Comment by kpango** [comment]
Resolved
